import * as dotenv from "dotenv";
import * as path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.resolve(__dirname, "../../.env") });

const N8N_BASE_URL = process.env.N8N_BASE_URL!;
const N8N_API_KEY = process.env.N8N_API_KEY!;
const GOOGLE_DRIVE_FOLDER_ID = "1I0BspHZEJNBTFb04Oq585LsQrFd7sny5";
const WORKFLOW_ID = "9Xw3q2PtO1LPC4JH";

const getRes = await fetch(`${N8N_BASE_URL}/api/v1/workflows/${WORKFLOW_ID}`, {
  headers: { "X-N8N-API-KEY": N8N_API_KEY },
});
const workflow = await getRes.json();
if (!getRes.ok) { console.error("❌", workflow); process.exit(1); }
console.log("✅ Fetched:", workflow.name);

// ── FIX 1: EMAIL NODE ─────────────────────────────────────────────────────────
//
//  PROBLEM: The analysis Claude writes is HTML (we just updated the prompts
//  to ask for HTML output). But the email was wrapping it inside a <p> tag
//  which makes it show as raw text.
//
//  FIX: The email message now directly embeds the HTML analysis.
//  Claude outputs <h1>, <h2>, <strong>, <ul> etc — those render natively
//  in Gmail as real headings, bold text, and bullet lists.
//
//  Think of it like this: Claude writes a nicely formatted web page.
//  The email just needs to copy-paste that page into the message body.

const emailIdx = workflow.nodes.findIndex((n: any) => n.name === "Gmail: Send Report Email");
if (emailIdx !== -1) {
  workflow.nodes[emailIdx].parameters = {
    operation: "send",
    toList: "4434lifeline@gmail.com",
    subject: "=SpyFu {{ $('Format Report Output').first().json.reportType }} Analysis Ready — {{ $('Format Report Output').first().json.date }}",
    emailType: "html",
    message: [
      "=<div style=\"font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto; color: #333;\">",
      "",
      "  <div style=\"background: #1a73e8; color: white; padding: 20px 24px; border-radius: 8px 8px 0 0;\">",
      "    <h2 style=\"margin:0\">SpyFu {{ $('Format Report Output').first().json.reportType }} Report</h2>",
      "    <p style=\"margin:4px 0 0; opacity:0.85\">Angel's Bail Bonds — {{ $('Format Report Output').first().json.date }}</p>",
      "  </div>",
      "",
      "  <div style=\"background: #f8f9fa; padding: 16px 24px; border-left: 4px solid #1a73e8;\">",
      "    <p style=\"margin:0\">📋 <strong>ClickUp Task:</strong> <a href=\"{{ $json.url }}\">{{ $('Format Report Output').first().json.taskName }}</a></p>",
      "    <p style=\"margin:4px 0 0\">📊 <strong>Report Type:</strong> {{ $('Format Report Output').first().json.reportType }}</p>",
      "  </div>",
      "",
      "  <div style=\"padding: 8px 24px;\">",
      "    <a href=\"{{ $json.url }}\" style=\"display:inline-block; background:#1a73e8; color:white; padding:12px 24px; text-decoration:none; border-radius:4px; margin:16px 0; font-weight:bold\">View in ClickUp →</a>",
      "  </div>",
      "",
      "  <hr style=\"border: 1px solid #e0e0e0; margin: 0 24px\">",
      "",
      "  <div style=\"padding: 16px 24px;\">",
      "    <h3 style=\"color:#1a73e8\">Full AI Analysis</h3>",
      "    {{ $('Format Report Output').first().json.analysis }}",
      "  </div>",
      "",
      "  <div style=\"background:#f1f3f4; padding:12px 24px; font-size:11px; color:#999; border-radius:0 0 8px 8px\">",
      "    Auto-generated by Angel's Bail Bonds SEO automation system.",
      "  </div>",
      "",
      "</div>",
    ].join("\n"),
    options: {},
  };
  console.log("✅ Fixed email node — analysis embeds as real HTML");
}

// ── FIX 2: GOOGLE DOCS — ADD CONTENT ─────────────────────────────────────────
//
//  PROBLEM: The Google Docs node was set to operation: "create" only.
//  "Create" just makes an empty document with a title — like opening a blank
//  notebook and writing only the cover. Nothing inside.
//
//  FIX: Add a second step right after Create that WRITES the analysis into
//  the document using the Google Docs API "batchUpdate" endpoint.
//
//  How it works:
//  Step 1 (existing): Create blank Google Doc → we get back a document ID
//  Step 2 (new):      Insert the analysis text at position 1 (the beginning)
//
//  The document ID from Step 1 is available as $json.documentId in Step 2.

// First, find and update the existing Google Docs node to save its position
const docsIdx = workflow.nodes.findIndex((n: any) => n.name === "Google Docs: Save Analysis");
if (docsIdx !== -1) {
  const docsNode = workflow.nodes[docsIdx];
  const docsPos = docsNode.position;

  // Rename the existing create node
  workflow.nodes[docsIdx].name = "Google Docs: Create Report";
  workflow.nodes[docsIdx].parameters = {
    operation: "create",
    title: "=SpyFu {{ $('Format Report Output').first().json.reportType }} Analysis — {{ $('Format Report Output').first().json.date }}",
    folderId: GOOGLE_DRIVE_FOLDER_ID,
  };

  // Add a new HTTP Request node to write the content using Google Docs API
  // It calls: POST https://docs.googleapis.com/v1/documents/{id}:batchUpdate
  // with an "insertText" request that puts the analysis at position 1 (start)
  const writeContentNode = {
    id: "node-docs-write-content",
    name: "Google Docs: Write Content",
    type: "n8n-nodes-base.httpRequest",
    typeVersion: 4.2,
    position: [docsPos[0] + 240, docsPos[1]],
    parameters: {
      method: "POST",
      // documentId comes from the Create node output ($json.documentId)
      url: "={{ 'https://docs.googleapis.com/v1/documents/' + $json.documentId + ':batchUpdate' }}",
      // Use the same Google OAuth credential as the Google Docs node
      authentication: "predefinedCredentialType",
      nodeCredentialType: "googleDocsOAuth2Api",
      sendBody: true,
      contentType: "raw",
      rawContentType: "application/json",
      // insertText at index 1 = the very beginning of the document body
      body: [
        "={{ JSON.stringify({",
        "  requests: [{",
        "    insertText: {",
        "      location: { index: 1 },",
        "      text: $('Format Report Output').first().json.analysis",
        "    }",
        "  }]",
        "}) }}",
      ].join("\n"),
      options: {},
    },
  };

  // Insert the write node after the create node
  workflow.nodes.splice(docsIdx + 1, 0, writeContentNode);

  // Update connections: Create → Write Content (end of chain)
  workflow.connections["Google Docs: Create Report"] = {
    main: [[{ node: "Google Docs: Write Content", type: "main", index: 0 }]],
  };
  // Also update whatever was pointing to "Google Docs: Save Analysis"
  for (const [nodeName, conns] of Object.entries(workflow.connections) as any) {
    if (nodeName === "Google Docs: Save Analysis") continue;
    for (const branch of conns.main || []) {
      for (const conn of branch || []) {
        if (conn.node === "Google Docs: Save Analysis") {
          conn.node = "Google Docs: Create Report";
        }
      }
    }
  }
  delete workflow.connections["Google Docs: Save Analysis"];

  console.log("✅ Fixed Google Docs — Create doc then Write content");
}

// ── PUSH BACK ─────────────────────────────────────────────────────────────────
const putRes = await fetch(`${N8N_BASE_URL}/api/v1/workflows/${WORKFLOW_ID}`, {
  method: "PUT",
  headers: { "X-N8N-API-KEY": N8N_API_KEY, "Content-Type": "application/json" },
  body: JSON.stringify({
    name: workflow.name,
    nodes: workflow.nodes,
    connections: workflow.connections,
    settings: workflow.settings,
    staticData: workflow.staticData ?? null,
  }),
});

const putData = await putRes.json();
if (putRes.ok) {
  console.log("\n✅ Workflow saved!");
  console.log("   Nodes:", putData.nodes.map((n: any) => n.name).join(" → "));
} else {
  console.error("❌", JSON.stringify(putData, null, 2));
}
